#!/usr/bin/env bash

tmp_dir=$(mktemp -d -t devcontainer-XXXXXXXXXX)

echo "Cloning the devcontainers tool to a temporary directory: $tmp_dir"

git clone --quiet https://github.com/jpslav/devcontainers.git $tmp_dir

echo "Installing the devcontainer files with $tmp_dir/install '$@'"

$tmp_dir/install "$@"